### ISSUE TITLE
Add ability to control number of times sound is played

### ISSUE THREAD

**Issue by yoshyoyo** [Novecento99/Scimia#7]
Hi,

Could you please add this feature where the user can control the number of times the sound is played, instead of just 10 times?

Thanks.

**Comment by Novecento99** [comment]
Hi, 
what do you mean? 
The sound is played every time you go over the treshold forever

**Comment by warden161** [comment]
An issue I've noticed with the app is that if I scream, for every second or whatever the wait is in the main loop it will play the sound

**Comment by Novecento99** [comment]
Yes it's true
It has to be addressed
I have no time these days but yes, it has to be corrected.
Old versions didn't have this bug

GL

Il Gio 9 Feb 2023, 02:04 warden161 ***@***.***> ha scritto:

**Comment by warden161** [comment]
I could PR this.

**Comment by Novecento99** [comment]
Would be nice, I would appreciate it

GL

Il Gio 9 Feb 2023, 19:59 warden161 ***@***.***> ha scritto:

**Comment by Novecento99** [comment]
i've fixed it
