### ISSUE TITLE
Add a way to save the threshold to a txt file

### ISSUE THREAD

**Issue by Iliano101** [Novecento99/Scimia#9]
### **Improvement Request**

**Current Behavior**
The script currently alerts users when the microphone input exceeds a specified loudness threshold. However, users need to manually enter the threshold each time the script is run, which can be inconvenient.

**Desired Behavior**
It would be beneficial to have a saving feature that allows users to set and save a default loudness threshold. This way, users don't have to manually input the threshold every time they run the script, enhancing user experience and making the tool more user-friendly.

**Comment by Novecento99** [comment]
Hi! Thankyou for your suggestion.
I graduated on December and will start to work in March; your issue reminded me of this software that I'm going to work on in these days!

**Comment by Novecento99** [comment]
done!

**Comment by Novecento99** [comment]
and honestly I didnt expect someone to still use it ahah
